#!/bin/sh

set +e

echo '
Loading Armbian-based GNU/Linux minimal OS for ARM-based CU board, please wait...
'

export MODPROBE_OPTIONS="-qb"
export PATH=/bin:/sbin:

[ -d '/dev/' ] || mkdir -m 0755 '/dev/'
[ -d /root ] || mkdir -m 0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc

mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc
mount -t devtmpfs -o nosuid,mode=0755,size=95% udev /dev

mkdir /dev/pts
mkdir -p '/var/lock'
mkdir -m 0777 '/dev/shm/'

mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts

ln -s '/dev/shm' '/tmp'
TMPDIR='/tmp'
export TMPDIR

(
    cat /proc/version /proc/mounts
    df
    dmesg
) >/dev/urandom

IP=10.0.0.22

case " $(cat /proc/cmdline) " in
init=*)
	init=${x#init=}
	;;
root=*)
	ROOT=${x#root=}
	if [ -z "${BOOT}" ] && [ "$ROOT" = "/dev/nfs" ]; then
		BOOT=nfs
	fi
	;;
rootflags=*)
	ROOTFLAGS="-o ${x#rootflags=}"
	;;
rootfstype=*)
	ROOTFSTYPE="${x#rootfstype=}"
	;;
ip=*)
	IP="${x#ip=}"
	;;
esac

# mdadm needs hostname to be set. This has to be done before the udev rules are called!
if [ -f "/etc/hostname" ]; then
    /bin/hostname -F /etc/hostname >/dev/null 2>&1
fi

##################
# CU boot script #
##################

set -x

# default networking
ip link set up dev eth0
ip addr add $IP/16 dev eth0

# mount CU /root fs
test -n "$ROOT" -a -n "$ROOTFSTYPE" && {
    mount -t "$ROOTFSTYPE" "-o${ROOTFLAGS:-ro}" "$ROOT" '/root/'
} || mount -t 'vfat' "-o${ROOTFLAGS:-ro}" '/dev/mmcblk0p1' '/root/'

# CU application run
cd '/root/CU-ARM' || cd '/root/cu-arm'
sh -c './run.sh' || sh -c './RUN.SH'

# by default loop with interactive shell otherwise
exec env sh -c '
while echo "? Respawn shell..."
do /bin/sh -i
done
'
# not reached; stops init script here
