#!/bin/sh

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
    mkimg)
        rm /dev/shm/initramfs-*
        mkinitramfs -o /dev/shm/initramfs-$(uname -r).img
        tar -czf /dev/shm/initramfs-tools.tar.gz /usr/share/initramfs-tools
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

set -x

##### setup initramfs with needed files required to execute `adani-cu-arm` applications #####

# use usual '/boot'
mkdir $DESTDIR/boot/
# copy needed shared libs & update ld cache for node.js binary
copy_exec /root/bin/node /boot/
# `node` binary is available on Flash drive with the application code, thus delete this
rm $DESTDIR/boot/node

# cleanup not needed stuff, `ip` is used to configure networking
rm $DESTDIR/bin/ifconfig
