#!/bin/sh

set +e -x

case "${1}" in
    prereqs)
        exit 0
    ;;
esac

# networking setup moved there as well
test -f /boot/adani-cu-arm/run.sh && sh /boot/adani-cu-arm/run.sh

# loop with interactive shell otherwise
while /bin/sh -i
do echo '? Respawn shell...'
done

exit 0
