#!/bin/sh

set +e -x

case "${1}" in
    prereqs)
        exit 0
    ;;
esac

# default networking
ip link set up dev eth0
ip addr add 192.168.1.22/16 dev eth0
ip addr add 10.0.0.22/16 dev eth0

# add compatible directory on RAM
test -d /dev/shm/ || mkdir /dev/shm/

# read-only Flash drive
mount /dev/mmcblk0p1 /boot/ -oro

test -f /boot/adani-cu-arm/run.sh && sh /boot/adani-cu-arm/run.sh

# loop with interactive shell otherwise
while /bin/sh -i
do echo '? Respawn shell...'
done

exit 0
